
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isDemoMode, createDemoClient } from '@/lib/demo';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wnmxgjrjrckwtyttidkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubXhnanJqcmNrd3R5dHRpZGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxOTU3MzcsImV4cCI6MjA1Mzc3MTczN30.uhtHBW6t8t6ofL2GLvnBy5Gr44cbH-jfp-jKxaXi8Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const realClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Usuarios normales reciben el cliente real SIN ningún wrapper (riesgo cero).
// Solo en modo demo (que siempre recarga la página al entrar/salir) se envuelve
// en un Proxy que intercepta from/auth/functions/storage para devolver datos mock
// sin tocar la base real.
export const supabase: typeof realClient = isDemoMode()
  ? (new Proxy(realClient, {
      get(target, prop, receiver) {
        const demo = createDemoClient();
        if (prop in demo) return (demo as any)[prop];
        return Reflect.get(target, prop, receiver);
      },
    }) as any)
  : realClient;

// Export the storage URL for easy access
export const STORAGE_URL = `${SUPABASE_URL}/storage/v1/object/public`;
